# Generated by Django 4.2 on 2023-07-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_members_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='course',
        ),
        migrations.RemoveField(
            model_name='members',
            name='dept',
        ),
    ]
