# Generated by Django 4.2 on 2023-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_members_course_remove_members_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
