# Generated by Django 4.2.3 on 2023-10-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
